spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: KELVYchuks49$

  jpa:
    show-sql: true
websiteUrl: http://localhost:4242