-- ---------------------------------------------------------------------------
-- Baseline schema (PostgreSQL).
--
-- This replaces the original 12 incremental MySQL migrations, which are kept
-- for reference in docs/legacy-mysql-migrations/. They were squashed rather
-- than translated because the project moved database engines before it ever
-- had production data to preserve: several of them (uuid_to_bin defaults,
-- INT UNSIGNED, MODIFY COLUMN, DROP FOREIGN KEY) have no direct PostgreSQL
-- equivalent, and replaying twelve versions of a schema nobody ran is noise.
-- ---------------------------------------------------------------------------

create table users
(
    id       bigint generated by default as identity primary key,
    name     varchar(255) not null,
    email    varchar(255) not null,
    password varchar(255) not null,
    role     varchar(20)  not null default 'USER',
    constraint users_email_unique unique (email)
);

create table addresses
(
    id      bigint generated by default as identity primary key,
    street  varchar(255) not null,
    city    varchar(255) not null,
    state   varchar(255) not null,
    zip     varchar(255) not null,
    user_id bigint       not null references users (id) on delete cascade
);

create index addresses_user_id_idx on addresses (user_id);

create table profiles
(
    id             bigint primary key references users (id) on delete cascade,
    bio            text,
    phone_number   varchar(15),
    date_of_birth  date,
    loyalty_points integer default 0
);

create table categories
(
    id   smallint generated by default as identity primary key,
    name varchar(255) not null,
    constraint categories_name_unique unique (name)
);

create table products
(
    id          bigint generated by default as identity primary key,
    name        varchar(255)   not null,
    description text           not null,
    price       numeric(10, 2) not null,
    image_url   varchar(500),
    category_id smallint references categories (id) on delete restrict
);

create index products_category_id_idx on products (category_id);

create table wishlist
(
    product_id bigint not null references products (id) on delete cascade,
    user_id    bigint not null references users (id) on delete cascade,
    constraint pk_wishlist primary key (product_id, user_id)
);

create table carts
(
    id           uuid primary key,
    date_created date not null default current_date
);

create table cart_items
(
    id         bigint generated by default as identity primary key,
    cart_id    uuid    not null references carts (id) on delete cascade,
    product_id bigint  not null references products (id) on delete cascade,
    quantity   integer not null default 1,
    constraint cart_items_cart_product_unique unique (cart_id, product_id),
    constraint cart_items_quantity_positive check (quantity > 0)
);

create table orders
(
    id          bigint generated by default as identity primary key,
    customer_id bigint         not null references users (id),
    status      varchar(20)    not null,
    created_at  timestamp      not null default now(),
    total_price numeric(10, 2) not null
);

create index orders_customer_id_idx on orders (customer_id);

create table order_items
(
    id          bigint generated by default as identity primary key,
    order_id    bigint         not null references orders (id) on delete cascade,
    product_id  bigint         not null references products (id),
    unit_price  numeric(10, 2) not null,
    quantity    integer        not null,
    total_price numeric(10, 2) not null
);

create index order_items_order_id_idx on order_items (order_id);
